In [12]:
import numpy as np

In [13]:
#Create array and convert to 3*3 matrix
a = np.array([1, 2, 3, 0, 1, 4, 5, 6, 0]).reshape(3, 3)


In [14]:
#Calculate inverse of set a
inverse_of_a = np.linalg.inv(a)
#its not necessary to print but you can always check for your cruosity
print(inverse_of_a)

[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [15]:
#Calculate product of a and inverse of a
product_1 = a@inverse_of_a
product_2 = inverse_of_a@a

In [16]:
#Create identity matrix
identity = np.identity(3)

In [17]:
#Check if product of set a with its inverse is equal to identity matrix
print(np.allclose(product_1, identity))
print(np.allclose(product_2, identity))

True
True
